## Stock Feature Engineering

This section transforms the cleaned stock dataset into a feature-rich dataset that can be used for anomaly detection.

The goal of feature engineering is to create meaningful numerical variables that describe stock behaviour and market context. These features are designed to capture:

- daily movement
- rolling risk
- short-term trend
- downside risk
- overall market behaviour
- stock movement relative to the market

The final output of this section is a clean feature dataset saved as `stock_features_daily.csv`, which is later used for anomaly detection and evaluation.

In [ ]:
# Load Clean Stock Dataset 

from pathlib import Path
import pandas as pd
import numpy as np

def find_project_root(start: Path) -> Path:
    start = start.resolve()
    for p in [start] + list(start.parents):
        if (p / "data").exists():
            return p
    return start

PROJECT_ROOT = find_project_root(Path.cwd())
DATA_DIR = PROJECT_ROOT / "data"
DATA_PROCESSED = DATA_DIR / "processed"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_PROCESSED exists:", DATA_PROCESSED.exists())

df = pd.read_csv(DATA_PROCESSED / "stocks_master_2014_2024.csv")

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values(["Ticker","Date"]).reset_index(drop=True)

print("Shape:", df.shape)
df.head()

PROJECT_ROOT: /Users/hansaninadeera/Desktop/MDSAI MORATUWA/course/3rd Semester/Capstone project/Capstone
DATA_PROCESSED exists: True
Shape: (57020, 8)

,Date,Open,High,Low,Close,Volume,Ticker,Sector
0,2014-01-02,16.500,16.750,16.250,16.250000,8804,ACL-N0000.CM,Industrial
1,2014-01-03,16.500,16.500,16.250,16.250000,481552,ACL-N0000.CM,Industrial
2,2014-01-06,16.250,16.250,16.000,16.200001,105144,ACL-N0000.CM,Industrial
3,2014-01-07,16.025,16.725,16.025,16.500000,216296,ACL-N0000.CM,Industrial
4,2014-01-08,16.625,16.625,16.625,16.625000,2092,ACL-N0000.CM,Industrial

In [ ]:
#  Daily Stock Return

df["Return"] = (
    df.groupby("Ticker")["Close"]
      .pct_change()
)

df.head(10)

,Date,Open,High,Low,Close,Volume,Ticker,Sector,Return
0,2014-01-02,16.500,16.750,16.250,16.250000,8804,ACL-N0000.CM,Industrial,NaN
1,2014-01-03,16.500,16.500,16.250,16.250000,481552,ACL-N0000.CM,Industrial,0.000000
2,2014-01-06,16.250,16.250,16.000,16.200001,105144,ACL-N0000.CM,Industrial,-0.003077
3,2014-01-07,16.025,16.725,16.025,16.500000,216296,ACL-N0000.CM,Industrial,0.018518
4,2014-01-08,16.625,16.625,16.625,16.625000,2092,ACL-N0000.CM,Industrial,0.007576
5,2014-01-09,16.625,16.750,16.625,16.750000,13412,ACL-N0000.CM,Industrial,0.007519
6,2014-01-10,16.750,17.475,16.750,17.325001,183580,ACL-N0000.CM,Industrial,0.034328
7,2014-01-13,17.475,17.500,17.250,17.250000,120808,ACL-N0000.CM,Industrial,-0.004329
8,2014-01-16,17.500,17.500,17.250,17.250000,63200,ACL-N0000.CM,Industrial,0.000000
9,2014-01-17,17.250,17.500,16.525,17.500000,84412,ACL-N0000.CM,Industrial,0.014493

In [ ]:
#30-Day Stock Volatility

df["Vol_30"] = (
    df.groupby("Ticker")["Return"]
      .rolling(30)
      .std()
      .reset_index(level=0, drop=True)
)

df.head(40)

,Date,Open,High,Low,Close,Volume,Ticker,Sector,Return,Vol_30
0,2014-01-02,16.500000,16.750000,16.250000,16.250000,8804,ACL-N0000.CM,Industrial,NaN,NaN
1,2014-01-03,16.500000,16.500000,16.250000,16.250000,481552,ACL-N0000.CM,Industrial,0.000000,NaN
2,2014-01-06,16.250000,16.250000,16.000000,16.200001,105144,ACL-N0000.CM,Industrial,-0.003077,NaN
3,2014-01-07,16.025000,16.725000,16.025000,16.500000,216296,ACL-N0000.CM,Industrial,0.018518,NaN
4,2014-01-08,16.625000,16.625000,16.625000,16.625000,2092,ACL-N0000.CM,Industrial,0.007576,NaN
5,2014-01-09,16.625000,16.750000,16.625000,16.750000,13412,ACL-N0000.CM,Industrial,0.007519,NaN
6,2014-01-10,16.750000,17.475000,16.750000,17.325001,183580,ACL-N0000.CM,Industrial,0.034328,NaN
7,2014-01-13,17.475000,17.500000,17.250000,17.250000,120808,ACL-N0000.CM,Industrial,-0.004329,NaN
8,2014-01-16,17.500000,17.500000,17.250000,17.250000,63200,ACL-N0000.CM,Industrial,0.000000,NaN
9,2014-01-17,17.250000,17.500000,16.525000,17.500000,84412,ACL-N0000.CM,Industrial,0.014493,NaN
10,2014-01-20,17.000000,17.000000,17.000000,17.000000,1200,ACL-N0000.CM,Industrial,-0.028571,NaN
11,2014-01-21,17.000000,17.000000,17.000000,17.000000,1200,ACL-N0000.CM,Industrial,0.000000,NaN
12,2014-01-22,17.000000,18.500000,17.000000,18.275000,192080,ACL-N0000.CM,Industrial,0.075000,NaN
13,2014-01-23,18.225000,18.475000,18.225000,18.450001,4000,ACL-N0000.CM,Industrial,0.009576,NaN
14,2014-01-24,18.200001,18.250000,18.075001,18.174999,192760,ACL-N0000.CM,Industrial,-0.014905,NaN
15,2014-01-27,17.549999,17.549999,17.500000,17.525000,6792,ACL-N0000.CM,Industrial,-0.035763,NaN
16,2014-01-28,17.825001,17.875000,17.825001,17.875000,3236,ACL-N0000.CM,Industrial,0.019971,NaN
17,2014-01-29,17.750000,17.750000,17.750000,17.750000,63200,ACL-N0000.CM,Industrial,-0.006993,NaN
18,2014-01-30,17.500000,17.500000,17.500000,17.500000,400,ACL-N0000.CM,Industrial,-0.014085,NaN
19,2014-01-31,17.500000,17.500000,17.250000,17.250000,44404,ACL-N0000.CM,Industrial,-0.014286,NaN
20,2014-02-03,17.375000,17.375000,17.375000,17.375000,3200,ACL-N0000.CM,Industrial,0.007246,NaN
21,2014-02-05,17.250000,17.250000,17.250000,17.250000,4820,ACL-N0000.CM,Industrial,-0.007194,NaN
22,2014-02-06,17.000000,17.250000,17.000000,17.000000,6112,ACL-N0000.CM,Industrial,-0.014493,NaN
23,2014-02-07,17.000000,17.250000,17.000000,17.000000,6112,ACL-N0000.CM,Industrial,0.000000,NaN
24,2014-02-10,16.275000,16.375000,16.275000,16.375000,40108,ACL-N0000.CM,Industrial,-0.036765,NaN
25,2014-02-11,16.275000,16.375000,16.275000,16.375000,40108,ACL-N0000.CM,Industrial,0.000000,NaN
26,2014-02-12,16.174999,16.250000,16.174999,16.200001,12080,ACL-N0000.CM,Industrial,-0.010687,NaN
27,2014-02-13,16.250000,16.250000,16.250000,16.250000,8000,ACL-N0000.CM,Industrial,0.003086,NaN
28,2014-02-17,16.250000,16.250000,16.125000,16.125000,20800,ACL-N0000.CM,Industrial,-0.007692,NaN
29,2014-02-18,16.250000,16.250000,16.125000,16.125000,20800,ACL-N0000.CM,Industrial,0.000000,NaN
30,2014-02-19,16.000000,16.000000,15.775000,16.000000,27204,ACL-N0000.CM,Industrial,-0.007752,0.020897
31,2014-02-20,15.775000,16.000000,15.775000,16.000000,432,ACL-N0000.CM,Industrial,0.000000,0.020897
32,2014-02-21,15.900000,16.000000,15.750000,16.000000,236280,ACL-N0000.CM,Industrial,0.000000,0.020891
33,2014-02-24,15.525000,16.125000,15.500000,15.500000,138440,ACL-N0000.CM,Industrial,-0.031250,0.021324
34,2014-02-25,15.500000,15.500000,15.000000,15.025000,546996,ACL-N0000.CM,Industrial,-0.030645,0.021875
35,2014-02-26,15.000000,16.100000,15.000000,15.025000,149772,ACL-N0000.CM,Industrial,0.000000,0.021792
36,2014-02-28,15.625000,15.975000,15.625000,15.975000,10080,ACL-N0000.CM,Industrial,0.063228,0.024039
37,2014-03-03,15.625000,15.625000,15.625000,15.625000,1200,ACL-N0000.CM,Industrial,-0.021909,0.024300
38,2014-03-04,15.625000,15.625000,15.625000,15.625000,8800,ACL-N0000.CM,Industrial,0.000000,0.024300
39,2014-03-05,15.625000,15.625000,15.625000,15.625000,400,ACL-N0000.CM,Industrial,0.000000,0.024083

In [ ]:
#20-Day Momentum

df["Mom_20"] = (
    df.groupby("Ticker")["Close"]
      .pct_change(20)
)

df.head(30)

,Date,Open,High,Low,Close,Volume,Ticker,Sector,Return,Vol_30,Mom_20
0,2014-01-02,16.500000,16.750000,16.250000,16.250000,8804,ACL-N0000.CM,Industrial,NaN,NaN,NaN
1,2014-01-03,16.500000,16.500000,16.250000,16.250000,481552,ACL-N0000.CM,Industrial,0.000000,NaN,NaN
2,2014-01-06,16.250000,16.250000,16.000000,16.200001,105144,ACL-N0000.CM,Industrial,-0.003077,NaN,NaN
3,2014-01-07,16.025000,16.725000,16.025000,16.500000,216296,ACL-N0000.CM,Industrial,0.018518,NaN,NaN
4,2014-01-08,16.625000,16.625000,16.625000,16.625000,2092,ACL-N0000.CM,Industrial,0.007576,NaN,NaN
5,2014-01-09,16.625000,16.750000,16.625000,16.750000,13412,ACL-N0000.CM,Industrial,0.007519,NaN,NaN
6,2014-01-10,16.750000,17.475000,16.750000,17.325001,183580,ACL-N0000.CM,Industrial,0.034328,NaN,NaN
7,2014-01-13,17.475000,17.500000,17.250000,17.250000,120808,ACL-N0000.CM,Industrial,-0.004329,NaN,NaN
8,2014-01-16,17.500000,17.500000,17.250000,17.250000,63200,ACL-N0000.CM,Industrial,0.000000,NaN,NaN
9,2014-01-17,17.250000,17.500000,16.525000,17.500000,84412,ACL-N0000.CM,Industrial,0.014493,NaN,NaN
10,2014-01-20,17.000000,17.000000,17.000000,17.000000,1200,ACL-N0000.CM,Industrial,-0.028571,NaN,NaN
11,2014-01-21,17.000000,17.000000,17.000000,17.000000,1200,ACL-N0000.CM,Industrial,0.000000,NaN,NaN
12,2014-01-22,17.000000,18.500000,17.000000,18.275000,192080,ACL-N0000.CM,Industrial,0.075000,NaN,NaN
13,2014-01-23,18.225000,18.475000,18.225000,18.450001,4000,ACL-N0000.CM,Industrial,0.009576,NaN,NaN
14,2014-01-24,18.200001,18.250000,18.075001,18.174999,192760,ACL-N0000.CM,Industrial,-0.014905,NaN,NaN
15,2014-01-27,17.549999,17.549999,17.500000,17.525000,6792,ACL-N0000.CM,Industrial,-0.035763,NaN,NaN
16,2014-01-28,17.825001,17.875000,17.825001,17.875000,3236,ACL-N0000.CM,Industrial,0.019971,NaN,NaN
17,2014-01-29,17.750000,17.750000,17.750000,17.750000,63200,ACL-N0000.CM,Industrial,-0.006993,NaN,NaN
18,2014-01-30,17.500000,17.500000,17.500000,17.500000,400,ACL-N0000.CM,Industrial,-0.014085,NaN,NaN
19,2014-01-31,17.500000,17.500000,17.250000,17.250000,44404,ACL-N0000.CM,Industrial,-0.014286,NaN,NaN
20,2014-02-03,17.375000,17.375000,17.375000,17.375000,3200,ACL-N0000.CM,Industrial,0.007246,NaN,0.069231
21,2014-02-05,17.250000,17.250000,17.250000,17.250000,4820,ACL-N0000.CM,Industrial,-0.007194,NaN,0.061538
22,2014-02-06,17.000000,17.250000,17.000000,17.000000,6112,ACL-N0000.CM,Industrial,-0.014493,NaN,0.049383
23,2014-02-07,17.000000,17.250000,17.000000,17.000000,6112,ACL-N0000.CM,Industrial,0.000000,NaN,0.030303
24,2014-02-10,16.275000,16.375000,16.275000,16.375000,40108,ACL-N0000.CM,Industrial,-0.036765,NaN,-0.015038
25,2014-02-11,16.275000,16.375000,16.275000,16.375000,40108,ACL-N0000.CM,Industrial,0.000000,NaN,-0.022388
26,2014-02-12,16.174999,16.250000,16.174999,16.200001,12080,ACL-N0000.CM,Industrial,-0.010687,NaN,-0.064935
27,2014-02-13,16.250000,16.250000,16.250000,16.250000,8000,ACL-N0000.CM,Industrial,0.003086,NaN,-0.057971
28,2014-02-17,16.250000,16.250000,16.125000,16.125000,20800,ACL-N0000.CM,Industrial,-0.007692,NaN,-0.065217
29,2014-02-18,16.250000,16.250000,16.125000,16.125000,20800,ACL-N0000.CM,Industrial,0.000000,NaN,-0.078571

In [ ]:
#Drawdown

rolling_max = (
    df.groupby("Ticker")["Close"]
      .cummax()
)

df["Drawdown"] = (df["Close"] / rolling_max) - 1

df.head(30)

,Date,Open,High,Low,Close,Volume,Ticker,Sector,Return,Vol_30,Mom_20,Drawdown
0,2014-01-02,16.500000,16.750000,16.250000,16.250000,8804,ACL-N0000.CM,Industrial,NaN,NaN,NaN,0.000000
1,2014-01-03,16.500000,16.500000,16.250000,16.250000,481552,ACL-N0000.CM,Industrial,0.000000,NaN,NaN,0.000000
2,2014-01-06,16.250000,16.250000,16.000000,16.200001,105144,ACL-N0000.CM,Industrial,-0.003077,NaN,NaN,-0.003077
3,2014-01-07,16.025000,16.725000,16.025000,16.500000,216296,ACL-N0000.CM,Industrial,0.018518,NaN,NaN,0.000000
4,2014-01-08,16.625000,16.625000,16.625000,16.625000,2092,ACL-N0000.CM,Industrial,0.007576,NaN,NaN,0.000000
5,2014-01-09,16.625000,16.750000,16.625000,16.750000,13412,ACL-N0000.CM,Industrial,0.007519,NaN,NaN,0.000000
6,2014-01-10,16.750000,17.475000,16.750000,17.325001,183580,ACL-N0000.CM,Industrial,0.034328,NaN,NaN,0.000000
7,2014-01-13,17.475000,17.500000,17.250000,17.250000,120808,ACL-N0000.CM,Industrial,-0.004329,NaN,NaN,-0.004329
8,2014-01-16,17.500000,17.500000,17.250000,17.250000,63200,ACL-N0000.CM,Industrial,0.000000,NaN,NaN,-0.004329
9,2014-01-17,17.250000,17.500000,16.525000,17.500000,84412,ACL-N0000.CM,Industrial,0.014493,NaN,NaN,0.000000
10,2014-01-20,17.000000,17.000000,17.000000,17.000000,1200,ACL-N0000.CM,Industrial,-0.028571,NaN,NaN,-0.028571
11,2014-01-21,17.000000,17.000000,17.000000,17.000000,1200,ACL-N0000.CM,Industrial,0.000000,NaN,NaN,-0.028571
12,2014-01-22,17.000000,18.500000,17.000000,18.275000,192080,ACL-N0000.CM,Industrial,0.075000,NaN,NaN,0.000000
13,2014-01-23,18.225000,18.475000,18.225000,18.450001,4000,ACL-N0000.CM,Industrial,0.009576,NaN,NaN,0.000000
14,2014-01-24,18.200001,18.250000,18.075001,18.174999,192760,ACL-N0000.CM,Industrial,-0.014905,NaN,NaN,-0.014905
15,2014-01-27,17.549999,17.549999,17.500000,17.525000,6792,ACL-N0000.CM,Industrial,-0.035763,NaN,NaN,-0.050136
16,2014-01-28,17.825001,17.875000,17.825001,17.875000,3236,ACL-N0000.CM,Industrial,0.019971,NaN,NaN,-0.031165
17,2014-01-29,17.750000,17.750000,17.750000,17.750000,63200,ACL-N0000.CM,Industrial,-0.006993,NaN,NaN,-0.037940
18,2014-01-30,17.500000,17.500000,17.500000,17.500000,400,ACL-N0000.CM,Industrial,-0.014085,NaN,NaN,-0.051491
19,2014-01-31,17.500000,17.500000,17.250000,17.250000,44404,ACL-N0000.CM,Industrial,-0.014286,NaN,NaN,-0.065041
20,2014-02-03,17.375000,17.375000,17.375000,17.375000,3200,ACL-N0000.CM,Industrial,0.007246,NaN,0.069231,-0.058266
21,2014-02-05,17.250000,17.250000,17.250000,17.250000,4820,ACL-N0000.CM,Industrial,-0.007194,NaN,0.061538,-0.065041
22,2014-02-06,17.000000,17.250000,17.000000,17.000000,6112,ACL-N0000.CM,Industrial,-0.014493,NaN,0.049383,-0.078591
23,2014-02-07,17.000000,17.250000,17.000000,17.000000,6112,ACL-N0000.CM,Industrial,0.000000,NaN,0.030303,-0.078591
24,2014-02-10,16.275000,16.375000,16.275000,16.375000,40108,ACL-N0000.CM,Industrial,-0.036765,NaN,-0.015038,-0.112466
25,2014-02-11,16.275000,16.375000,16.275000,16.375000,40108,ACL-N0000.CM,Industrial,0.000000,NaN,-0.022388,-0.112466
26,2014-02-12,16.174999,16.250000,16.174999,16.200001,12080,ACL-N0000.CM,Industrial,-0.010687,NaN,-0.064935,-0.121951
27,2014-02-13,16.250000,16.250000,16.250000,16.250000,8000,ACL-N0000.CM,Industrial,0.003086,NaN,-0.057971,-0.119241
28,2014-02-17,16.250000,16.250000,16.125000,16.125000,20800,ACL-N0000.CM,Industrial,-0.007692,NaN,-0.065217,-0.126016
29,2014-02-18,16.250000,16.250000,16.125000,16.125000,20800,ACL-N0000.CM,Industrial,0.000000,NaN,-0.078571,-0.126016

In [ ]:
# Load ASPI Data (Correct Path)

ASPI_PATH = PROJECT_ROOT / "data" / "raw" / "aspi" / "ASPI_2014_2024_raw.csv"

aspi = pd.read_csv(ASPI_PATH)

aspi["Date"] = pd.to_datetime(aspi["Date"])

aspi = aspi.sort_values("Date").reset_index(drop=True)

print("ASPI shape:", aspi.shape)
print("ASPI min date:", aspi["Date"].min())
print("ASPI max date:", aspi["Date"].max())

aspi.head()

ASPI shape: (1778, 6)
ASPI min date: 2014-01-02 00:00:00
ASPI max date: 2021-09-30 00:00:00

        Date         Open         High          Low        Close    Volume
0 2014-01-02  5913.479980  5972.100098  5912.779785  5968.040039  28247700
1 2014-01-03  5968.359863  6007.790039  5956.709961  5973.799805  47510500
2 2014-01-06  5974.500000  5975.000000  5938.259766  5944.990234  23959600
3 2014-01-07  5945.049805  5989.419922  5942.620117  5977.069824  25385500
4 2014-01-08  5975.020020  6064.689941  5973.240234  6054.470215  49248500

In [ ]:
#Proxy Market Return (Equal Weighted)

market_proxy = (
    df.groupby("Date")["Return"]
      .mean()
      .reset_index()
      .rename(columns={"Return": "Market_Return"})
)

print("Proxy market shape:", market_proxy.shape)
market_proxy.head()

Proxy market shape: (2776, 2)

        Date  Market_Return
0 2014-01-02            NaN
1 2014-01-03      -0.000527
2 2014-01-06      -0.003602
3 2014-01-07       0.005202
4 2014-01-08       0.016692

In [ ]:
# Proxy Market 30-Day Volatility

market_proxy["Market_Vol_30"] = (
    market_proxy["Market_Return"]
      .rolling(30)
      .std()
)

market_proxy.head(40)

         Date  Market_Return  Market_Vol_30
0  2014-01-02            NaN            NaN
1  2014-01-03      -0.000527            NaN
2  2014-01-06      -0.003602            NaN
3  2014-01-07       0.005202            NaN
4  2014-01-08       0.016692            NaN
5  2014-01-09      -0.002088            NaN
6  2014-01-10       0.016432            NaN
7  2014-01-13       0.003895            NaN
8  2014-01-16       0.006831            NaN
9  2014-01-17      -0.004625            NaN
10 2014-01-20      -0.002255            NaN
11 2014-01-21       0.000609            NaN
12 2014-01-22       0.020696            NaN
13 2014-01-23      -0.000002            NaN
14 2014-01-24       0.006840            NaN
15 2014-01-27      -0.009534            NaN
16 2014-01-28      -0.000326            NaN
17 2014-01-29       0.002787            NaN
18 2014-01-30      -0.001982            NaN
19 2014-01-31       0.004876            NaN
20 2014-02-03      -0.004559            NaN
21 2014-02-05      -0.010897            NaN
22 2014-02-06      -0.001494            NaN
23 2014-02-07      -0.002602            NaN
24 2014-02-10      -0.011975            NaN
25 2014-02-11       0.003541            NaN
26 2014-02-12      -0.005107            NaN
27 2014-02-13      -0.000700            NaN
28 2014-02-17      -0.008312            NaN
29 2014-02-18      -0.008841            NaN
30 2014-02-19      -0.005328       0.007856
31 2014-02-20      -0.005459       0.007921
32 2014-02-21      -0.000051       0.007893
33 2014-02-24      -0.008236       0.007973
34 2014-02-25      -0.007632       0.007393
35 2014-02-26       0.009241       0.007631
36 2014-02-28       0.015319       0.007547
37 2014-03-03      -0.006853       0.007569
38 2014-03-04      -0.001123       0.007416
39 2014-03-05       0.003112       0.007437

In [ ]:
#  Merge Proxy Market to Stock Data

df = df.merge(market_proxy, on="Date", how="left")

print("Shape after merge:", df.shape)
df.head()

Shape after merge: (57020, 14)

,Date,Open,High,Low,Close,Volume,Ticker,Sector,Return,Vol_30,Mom_20,Drawdown,Market_Return,Market_Vol_30
0,2014-01-02,16.500,16.750,16.250,16.250000,8804,ACL-N0000.CM,Industrial,NaN,NaN,NaN,0.000000,NaN,NaN
1,2014-01-03,16.500,16.500,16.250,16.250000,481552,ACL-N0000.CM,Industrial,0.000000,NaN,NaN,0.000000,-0.000527,NaN
2,2014-01-06,16.250,16.250,16.000,16.200001,105144,ACL-N0000.CM,Industrial,-0.003077,NaN,NaN,-0.003077,-0.003602,NaN
3,2014-01-07,16.025,16.725,16.025,16.500000,216296,ACL-N0000.CM,Industrial,0.018518,NaN,NaN,0.000000,0.005202,NaN
4,2014-01-08,16.625,16.625,16.625,16.625000,2092,ACL-N0000.CM,Industrial,0.007576,NaN,NaN,0.000000,0.016692,NaN

In [ ]:
# Relative Return


df["Rel_Return"] = df["Return"] - df["Market_Return"]

df.head(10)

,Date,Open,High,Low,Close,Volume,Ticker,Sector,Return,Vol_30,Mom_20,Drawdown,Market_Return,Market_Vol_30,Rel_Return
0,2014-01-02,16.500,16.750,16.250,16.250000,8804,ACL-N0000.CM,Industrial,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
1,2014-01-03,16.500,16.500,16.250,16.250000,481552,ACL-N0000.CM,Industrial,0.000000,NaN,NaN,0.000000,-0.000527,NaN,0.000527
2,2014-01-06,16.250,16.250,16.000,16.200001,105144,ACL-N0000.CM,Industrial,-0.003077,NaN,NaN,-0.003077,-0.003602,NaN,0.000525
3,2014-01-07,16.025,16.725,16.025,16.500000,216296,ACL-N0000.CM,Industrial,0.018518,NaN,NaN,0.000000,0.005202,NaN,0.013316
4,2014-01-08,16.625,16.625,16.625,16.625000,2092,ACL-N0000.CM,Industrial,0.007576,NaN,NaN,0.000000,0.016692,NaN,-0.009117
5,2014-01-09,16.625,16.750,16.625,16.750000,13412,ACL-N0000.CM,Industrial,0.007519,NaN,NaN,0.000000,-0.002088,NaN,0.009607
6,2014-01-10,16.750,17.475,16.750,17.325001,183580,ACL-N0000.CM,Industrial,0.034328,NaN,NaN,0.000000,0.016432,NaN,0.017896
7,2014-01-13,17.475,17.500,17.250,17.250000,120808,ACL-N0000.CM,Industrial,-0.004329,NaN,NaN,-0.004329,0.003895,NaN,-0.008224
8,2014-01-16,17.500,17.500,17.250,17.250000,63200,ACL-N0000.CM,Industrial,0.000000,NaN,NaN,-0.004329,0.006831,NaN,-0.006831
9,2014-01-17,17.250,17.500,16.525,17.500000,84412,ACL-N0000.CM,Industrial,0.014493,NaN,NaN,0.000000,-0.004625,NaN,0.019118

In [ ]:
# Drop Initial NaNs


feature_cols = [
    "Return",
    "Vol_30",
    "Mom_20",
    "Drawdown",
    "Market_Return",
    "Market_Vol_30",
    "Rel_Return"
]

df_clean = df.dropna(subset=feature_cols).copy()

print("Original rows:", len(df))
print("After dropna:", len(df_clean))

df_clean.head()

Original rows: 57020
After dropna: 56390

,Date,Open,High,Low,Close,Volume,Ticker,Sector,Return,Vol_30,Mom_20,Drawdown,Market_Return,Market_Vol_30,Rel_Return
30,2014-02-19,16.000,16.000,15.775,16.000,27204,ACL-N0000.CM,Industrial,-0.007752,0.020897,-0.058824,-0.132791,-0.005328,0.007856,-0.002424
31,2014-02-20,15.775,16.000,15.775,16.000,432,ACL-N0000.CM,Industrial,0.000000,0.020897,-0.058824,-0.132791,-0.005459,0.007921,0.005459
32,2014-02-21,15.900,16.000,15.750,16.000,236280,ACL-N0000.CM,Industrial,0.000000,0.020891,-0.124487,-0.132791,-0.000051,0.007893,0.000051
33,2014-02-24,15.525,16.125,15.500,15.500,138440,ACL-N0000.CM,Industrial,-0.031250,0.021324,-0.159892,-0.159892,-0.008236,0.007973,-0.023014
34,2014-02-25,15.500,15.500,15.000,15.025,546996,ACL-N0000.CM,Industrial,-0.030645,0.021875,-0.173315,-0.185637,-0.007632,0.007393,-0.023014

In [ ]:
# Save Clean Feature Dataset


OUTPUT_PATH = DATA_PROCESSED / "stock_features_daily.csv"

df_clean.to_csv(OUTPUT_PATH, index=False)

print("Saved successfully.")
print("Final shape:", df_clean.shape)

Saved successfully.
Final shape: (56390, 15)